# frozen_string_literal: true

source 'https://rubygems.org'

gem 'activesupport'
gem 'passbook'
gem 'sinatra'

group :development do
  gem 'dotenv'
  gem 'pry'
  gem 'relaxed-rubocop'
  gem 'rubocop'
end
