name: CI
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
    branches:
      - develop
      - main
jobs:
  rubocop:
    if: github.event.pull_request.draft == false
    name: Rubocop
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.2
      - name: Rubocop
        run: |
          gem install relaxed-rubocop
          gem install rubocop
          rubocop
  rspec:
    if: github.event.pull_request.draft == false
    name: RSpec
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.2
      - name: Bundler Cache
        uses: pat-s/always-upload-cache@v2.1.3
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - name: Bundle Install
        run: |
          gem install bundler
          bundle install --path vendor/bundle
      - name: Rspec
        run: bundle exec rspec
